FROM alpine:latest

# Docker file labels
LABEL description="Proof of Concept image for a StrongSwan VM."
LABEL version="1.0"
LABEL maintainer="Eric Wu (https://github.com/e-wu)"

RUN apk --no-cache add --update strongswan 




